### ISSUE TITLE
ModuleNotFoundError: No module named 'eerie.nn.functional.bconv'

### ISSUE THREAD

**Issue by ZichenMiao** [dwromero/wavelet_networks#1]
It seems that the 'bconv.py' file is missing in 'eerie/nn/functional/'.

**Comment by dwromero** [comment]
Hi Zichen, sorry for my late response. The bconv.py file is not necessary. I might have forgotten to put its requirement away somewhere. Could you please tell me which experiments / files were you trying to run? 

Thanks for the hands-up! 
David
